config/routes.rb
Rails.application.routes.draw do

  root 'playlists#top_page'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

  resources :playlists do
    resources :comments, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :favorites, only: [:create] do
      collection do
        delete '/:user_id', controller: :favorites, action: :destroy, as: :destroy
      end
    end
    resources :musics, only: [:new, :create, :destroy] do
      collection do
        post :search
      end
    end
    collection do
      get :timeline
      get :ranking
      get :genre
      get 'genre/:id', controller: :playlists, action: :each_genre, as: :each_genre
    end
  end

  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :favorites
      get :follow
      get :follower
    end
  end

  namespace :admin do
    resources :playlists, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessor :title, :comment, :genre, :count_fav
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :musics
  enum genre: %i(pops rock jazz classic others)
  validates :title, presence: true
  

  def self.ranking(date, genre)
    if date.present?
      case date
      when "today"
        from = Time.now.at_beginning_of_day
        to = from + 1.day
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      when "week"
        from = Time.now.at_beginning_of_week
        to = from + 1.week
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      when "month"
        from = Time.now.at_beginning_of_month
        to = from + 1.month
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      end
    elsif genre.present?
      case genre
      when "pops"
        self.where(genre: 0).order(count_fav: :desc, created_at: :desc).limit(10)
      when "rock"
        self.where(genre: 1).order(count_fav: :desc, created_at: :desc).limit(10)
      when "jazz"
        self.where(genre: 2).order(count_fav: :desc, created_at: :desc).limit(10)
      when "classic"
        self.where(genre: 3).order(count_fav: :desc, created_at: :desc).limit(10)
      when "others"
        self.where(genre: 4).order(count_fav: :desc, created_at: :desc).limit(10)
      end
    else
      self.order("count_fav DESC, created_at DESC").limit(20)
    end
  end

  #playlistのデータ使ってないじゃん
  #date, genre両方引数にとったらこんらん
  #他の人だったらどう使うか、伝わりやすさが大事
  #意図が伝わりやすく
  #メソッドだけで表しづらければクラスを作ってしまう。
  #引数わかりやすく
  #プログラミングは思いやり。そもそも読みやすくしてある理由を考える。複数人での開発がスムーズにいくようにする意識を持つ。
  def date_ranking_title(date)
      case date
      when "today"
        "本日のランキング"
      when "week"
        "週間ランキング"
      when "month"
        "月間ランキング"
      end
  end
  
  def genre_ranking_title(genre)
      case genre
      when "pops"
        "PopsランキングTop10"
      when "rock"
        "RockランキングTop10"
      when "jazz"
        "JazzランキングTop10"
      when "classic"
        "ClassicランキングTop10"
      when "others"
        "OthersランキングTop10"
      end
  end

end

app/controllers/admin/playlists_controller.rb
class Admin::PlaylistsController < Admin::AdminController
  def index
    @playlists = Playlist.all.order("updated_at DESC")
    @playlist_user_ids = @playlists.pluck(:user_id)
    @user_name_array = Array.new
    @playlist_user_ids.each do |user_id|
      user_name = User.find(user_id).name
      @user_name_array << user_name
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @user = User.find(@playlist.user_id)
    @comments = Comment.where(playlist_id: params[:id])
    @comment_user_ids = @comments.pluck(:user_id)
    ## @user_ids をわかりやすい命名に
    ### 変数多い
    #viewで使わない変数は＠をつけない
    @user_name_array = Array.new
    @comment_user_ids.each do |user_id|
      user_name = User.find(user_id).name
      @user_name_array << user_name
    end
    #インスタンスメソッドとレシーバを意識して、ここのメソッドを修正
    @musics = Music.where(playlist_id: params[:id])
    music = Music.new(playlist_id: params[:id])
    @http = music.http
  end

  def destroy
    @playlist = Playlist.find_by(id: params[:id])
    @playlist.destroy
    redirect_to admin_playlists_path
  end



end

app/controllers/playlists_controller.rb
require 'rubygems'
require 'httparty'

class PlaylistsController < UsersController

  def after_sign_in_path_for(user)
    ranking_playlists_path
  end

#  before_action :authenticate_user!, except: :top_page
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  def top_page
    render layout: 'top_page'
  end

  def index
    @playlists = Playlist.all.order("updated_at DESC")
  end

  def show
    @playlist = Playlist.find(params[:id])
    @comments = Comment.where(playlist_id: params[:id])
    @status = Relationship.where(follower_id: current_user.id, followed_id: @playlist.user.id).present?
    favorite = Favorite.find_by(playlist_id: params[:id], user_id: current_user.id)
    if favorite.present?
      @condition = true
    else
      @condition = false
    end
    music = Music.new(playlist_id: params[:id])
    @http = music.movie_http
  end

  def new
    @playlist = Playlist.new
  end

  def create
    playlist = Playlist.new(playlist_params)
    if playlist.save
      redirect_to playlists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to playlist_path(id: params[:id])
    else
      flash[:alert] = "Can't be blank!"
      render 'edit'
    end
  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to playlists_path
  end

  def timeline
    follows = Relationship.where(follower_id: current_user.id).pluck(:followed_id)
    @follows = User.where(id: follows)
    @playlists = Playlist.where(user_id: follows).order("updated_at DESC").limit(20)
  end

  def genre
  end

  def each_genre
    @genre = params[:id]
    @playlists = Playlist.where(genre: @genre)
  end

  ## ここにも怪しげなコードがあった
  def ranking
    @playlists = Playlist.ranking(params[:date], params[:genre])
    @playlist_user_ids = @playlists.pluck(:user_id)
    playlist = Playlist.new
    #変なインスタンスメソッドを作って使用しているが、classを作ってやり直すのは時間かかるということでしのさんと話し、ここはそのままで。
    if params[:date].present?
      @title = playlist.date_ranking_title(params[:date])
    elsif params[:genre].present?
      @title = playlist.genre_ranking_title(params[:genre])
    else
      @title = "総合ランキング"
    end
  end

  private
  def playlist_params
    params.require(:playlist).permit(:user_id, :title, :comment, :genre)
  end
  
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/helpers/admin/playlists_helper.rb
module Admin::PlaylistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/admin/playlists/index.html.erb
<h2>プレイリスト一覧</h2>
<div class="container-fluid">
  <div class="row">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>プレイリスト名</th>
          <th>お気に入り数</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <% i = 0 %>
      <% @playlists.each do |playlist| %>
        <tbody>
          <tr>
            <td>
              <%= link_to @user_name_array[i], admin_user_path(id: @playlist_user_ids[i]) %>
              </td>
            <% i += 1 %>
            <td>
              <%= link_to playlist.title, admin_playlist_path(id: playlist.id) %>
              </td>
            <td>
                <%= playlist.favorites.count %>
              </td>
            <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>
              <td>
              <%= link_to "プレイリスト削除", admin_playlist_path(id: playlist.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/playlists/show.html.erb
<h2 id="title" value="<%= @playlist.id%>">Title : <%= @playlist.title %></h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-5">
      <div class="panel panel-default">
        <div class="panel-heading">Making User</div>
        <div class="panel-body">
          <%= link_to @user.name, admin_user_path(:id => @user.id), id: :user %>
          <%= link_to 'ユーザー削除', admin_user_path(id: @user.name), method: :delete, data: {:confirm => "Are you sure?"}, id: "comment_destroy", class: "btn btn-warning btn-xs" %>
        </div>

        <div class="panel-heading">Genre</div>
        <div class="panel-body">
          <%= @playlist.genre %>
        </div>

        <div class="panel-heading">Comment from Making User</div>
        <div class="panel-body">
          <%= @playlist.comment %>
        </div>
      </div>

      <br />

      <div id="comments">
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>コメント内容</th>
              <th>ユーザー名</th>
              <th>投稿日時</th>
            </tr>
          </thead>
          <% i = 0 %>
          <% @comments.each do |comment| %>
            <tbody>
              <tr>
                <td>
                  <%= comment.content %>
                </td>
                <td>
                  <%= link_to @user_name_array[i], admin_user_path(id: @comment_user_ids[i]) %>
                </td>
                <td>
                  <% create_time = comment.created_at %>
                  <%= create_time.strftime("%Y-%m-%d %H:%M:%S") %>
                </td>
                <td>
                  <%= link_to 'コメント削除', admin_playlist_comment_path(:playlist_id => @playlist.id, :id => comment.id), method: :delete, data: {:confirm => "Are you sure?"},  id: "comment_destroy", class: "btn btn-warning btn-xs" %>
                  <% i += 1 %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
      </div>

    </div>

    <div class="col-sm-7">

      <% if @http.nil? %>
        <h4>プレイリストに曲が登録されていません。</h4>
      <% else %>
        <h4>プレイリストの曲詳細</h4>
        <table class="table table-striped table-hover ">
          <thead>
            <tr>
              <th>曲順</th>
              <th>タイトル</th>
            </tr>
          </thead>
          <% i = 0 %>
          <% @musics.each do |music| %>
            <tbody>
              <tr>
                <td>
                  <%= i += 1 %>曲目
                </td>
                <td>
                  <%= music.title %>
                </td>
              </tr>
            </tbody>
          <% end %>
        </table>
        <iframe width="560" height="315" src=<%= @http %> frameborder="0" allowfullscreen>  
        </iframe>
      <% end %>

      <div>
        <%= link_to "プレイリスト削除", admin_playlist_path(id: @playlist.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
      </div>

    </div>
  </div>
</div>