config/routes.rb
Rails.application.routes.draw do

  root 'playlists#top_page'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

  resources :playlists do
    resources :comments, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :favorites, only: [:create] do
      collection do
        delete '/:user_id', controller: :favorites, action: :destroy, as: :destroy
      end
    end
    resources :musics, only: [:new, :create, :destroy] do
      collection do
        post :search
      end
    end
    collection do
      get :timeline
      get :ranking
      get :genre
      get 'genre/:id', controller: :playlists, action: :each_genre, as: :each_genre
    end
  end

  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :favorites
      get :follow
      get :follower
    end
  end

  namespace :admin do
    resources :playlists, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :playlists
  has_many :comments
  validates :name, presence: true
  validates :birth_date, presence: true
  validates :bd_open, presence: true
  validates :gender, presence: true

  # あなたがフォロー
  # has_many :relationships, :dependent => :destroy
  # has_many :followers, :through => :relationships

  # あなたをフォロー
  # has_many :followerships, :class_name => 'Relationship', :foreign_key => :follower_id, :dependent => :destroy
  # has_many :follwowers, :through => :followerships, :source => :user
  
  # enum gender: {man: 0, woman: 1} と同じ
  enum gender: %i(man woman)
  enum fav_music_genre: %i(pops rock jazz classic others)
  enum bd_open: %i(open not_open)

  mount_uploader :image, ImageUploader
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  def index
    @users = User.all
    user_ids = @users.pluck(:id)
    id_amount = user_ids.count
    id_amount
    @follower_amount_array = Array.new
    @followed_amount_array = Array.new
    for i in 1..id_amount do
      @follower_amount_array << Relationship.where(follower_id: user_ids[i]).count
      @followed_amount_array << Relationship.where(followed_id: user_ids[i]).count
      i += 1
    end
  end

  def show
    @user = User.find_by(id: params[:id])
    @playlists = Playlist.where(user_id: params[:id])
    @follower_amount = Relationship.where(follower_id: params[:id]).count
  end

  def destroy
    @user = User.find_by(id: params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  def new
    super
  end

  def create
    # deliverメソッドを使って、メールを送信する
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_flashing_format?
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
        SignUpMailer.sign_up_email(@user).deliver
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
        SignUpMailer.sign_up_email(@user).deliver
      end
    else
      clean_up_passwords resource
      respond_with resource
    end
  end

  def after_sign_up_path_for(user)
    playlists_path
  end

  def after_inactive_sign_up_path_for(user)
    playlists_path
  end

  def after_update_path_for(user)
    playlists_path
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_up) << [:name, :birth_date, :gender]
      devise_parameter_sanitizer.for(:account_update) << [:name, :birth_date, :bd_open, :gender, :fav_music_genre, :comment, :image]
    end

end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  def new
    super
  end

  def create
    super
  end

    protected
      def configure_permitted_parameters
        devise_parameter_sanitizer.for(:sign_up) << [:name, :birth_date, :gender]
        devise_parameter_sanitizer.for(:account_update) << [:name, :birth_date, :bd_open, :gender, :fav_music_genre, :comment]
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
#  before_action :authenticate_user!
  layout 'application'
  def after_sign_in_path_for(user)
    playlists_path
  end

  def show
    @user = User.find_by(id: params[:id])
    @fav_count = Favorite.where(user_id: params[:id]).count
    @playlists = Playlist.where(user_id: params[:id])
    @status = Relationship.where(follower_id: current_user.id, followed_id: params[:id]).present?
    @follower_amount = Relationship.where(follower_id: params[:id]).count
  end

  def favorites
    favorites = Favorite.where(user_id: params[:id]).pluck(:playlist_id)
    @playlists = Playlist.where(id: favorites)
  end

  def make_follow
    relationship = Relationship.new(follower_id: params[:follower_id], followed_id: params[:followed_id])
    relationship.save
    redirect_to :back
  end

  def delete_follow
    relationship = Relationship.find_by(follower_id: params[:follower_id], followed_id: params[:followed_id])
    relationship.destroy
    redirect_to :back
  end

  def follow
    relationships = Relationship.where(:follower_id => params[:id]).pluck(:followed_id)
    @users = User.where(id: relationships)
  end

  def follower
    relationships = Relationship.where(:followed_id => params[:id]).pluck(:follower_id)
    @users = User.where(id: relationships)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/_follow.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-5">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>#</th>
            <th>ユーザー名</th>
          </tr>
        </thead>
        <% i = 0 %>
        <% @users.each do |user|%>
          <tbody>
            <tr>
              <td>
                <%= i += 1 %>
              </td>
              <td>
                <%= link_to user.name, user_path(id: user.id) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/_follower.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-5">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>#</th>
            <th>ユーザー名</th>
          </tr>
        </thead>
        <% i = 0 %>
        <% @users.each do |user|%>
          <tbody>
            <tr>
              <td>
                <%= i += 1 %>
              </td>
              <td>
                <%= link_to user.name, user_path(id: user.id) %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/_profile.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default">
        <div class="panel-heading">名前</div>
        <div class="panel-body">
          <%= @user.name %>
        </div>
        <div class="panel-heading">プロフィール写真</div>
        <div class="panel-body">
      <% if @user.image? %>
        <%= image_tag @user.image.normal.url %>
      <% else %>
        <%= image_tag 'noimage.gif' %>
      <% end %>
        </div>
        <div class="panel-heading">性別</div>
        <div class="panel-body">
          <%= @user.gender %>
        </div>
        <div class="panel-heading">年齢</div>
        <div class="panel-body">
          <% if @user.bd_open %>
            年齢：
            <% d1 = @user.birth_date.strftime("%Y%m%d").to_i %>
            <% d2 = Date.today.strftime("%Y%m%d").to_i %>
            <%= (d2 - d1)/10000 %>歳
          <% else %>
            非公開
          <% end %><br />
        </div>
        <div class="panel-heading">好きな音楽のジャンル</div>
        <div class="panel-body">
          <%= @user.fav_music_genre %><br />
        </div>
        <div class="panel-heading">自己紹介</div>
        <div class="panel-body">
          <%= @user.comment %>
        </div>
      </div>

app/views/users/favorites.html.erb
<h2>お気に入り一覧</h2>

<div class="container-fluid">
  <div class="row">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>ユーザー名</th>
          <th>プレイリスト名</th>
          <th>お気に入り数</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <% @playlists.each do |playlist| %>
        <tbody>
          <tr>
            <td>
              <%= link_to playlist.user.name, user_path(id: playlist.user.id) %>
            </td>
            <td>
              <%= link_to playlist.title, playlist_path(id: playlist.id) %>
            </td>
              <td>
                <%= playlist.favorites.count %>
                </td>
            <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>
              <td>
              <%= link_to "お気に入りから削除", destroy_playlist_favorites_path(playlist_id: playlist.id, user_id: current_user.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-warning" %>
                </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>
</div>

app/views/users/follow.html.erb
<h2>Follow</h2>

<div>
  <%= render 'follow' %>
</div>

app/views/users/follower.html.erb
<h2>Follower</h2>

<div>
  <%= render 'follower' %>
</div>

app/views/users/my_follow.html.erb
<h2>My Follow</h2>

<div>
  <%= render 'follow' %>
</div>

app/views/users/my_follower.html.erb
<h2>My Follower</h2>

<div>
  <%= render 'follower' %>
</div>

app/views/users/my_playlists.html.erb
<h2>マイページ</h2>

<h4>自分の作成したプレイリスト一覧</h4>

  <div class="col-sm-12">
    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>プレイリスト名</th>
          <th>お気に入り数</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <% i = 0 %>
      <% @playlists.each do |playlist| %>
        <tbody>
          <tr>
            <td>
              <%= link_to playlist.title, playlist_path(id: playlist.id) %>
            </td>
            <td>
              <%= playlist.favorites.count %>
            </td>
            <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>
              <td>
    <%= link_to '登録曲編集', new_playlist_music_path(playlist_id: playlist.id), class: "btn btn-default" %>
    <%= link_to 'プレイリスト編集', edit_playlist_path(id: playlist.id), class: "btn btn-default" %>
              <%= link_to "削除", playlist_path(id: playlist.id), method: :delete, data: {confirm: "Are you sure?"}, class: "btn btn-danger" %>
              </td>
          </tr>
        </tbody>
      <% end %>
    </table>
  </div>

app/views/users/mypage.html.erb
<h2>マイページ</h2>

<%= render 'profile' %>
    </div>

<div class="col-sm-6">
  <ul class="list-group">
    <li class="list-group-item">
    <span class="badge"><%= @follower_amount %></span>
    <%= link_to 'follow', my_follow_user_path(id: current_user.id) %>
    </li>
    <li class="list-group-item">
    <span class="badge"><%= @followed_amount %></span>
    <%= link_to 'follower', my_follower_user_path(id: current_user.id) %>
    </li>
  </ul>
  <ul class="list-group">
    <li class="list-group-item">
    <span class="badge"><%= @my_playlists_amount %></span>
    <%= link_to '自分の作成したプレイリスト一覧', my_playlists_users_path %>
    </li>
    </ul>
</div>
  </div>
</div>

app/views/users/show.html.erb
<h2>プロフィール</h2>
<div class="row">
  <div>
    <% if @user.id == current_user.id %>
    <% else %>
      <% if @status == true %>
        <%= link_to 'フォロー中', user_relationship_path(:user_id => @user.id), method: :delete, class: "btn btn-primary" %>
      <% else %>
        <%= link_to 'フォローする', user_relationships_path(:user_id => @user.id), method: :post, class: "btn btn-primary" %>
      <% end %>
    <% end %>
  </div>

  <br />
  <%= render 'profile' %>

  <ul class="list-group">
    <li class="list-group-item">
    <span class="badge"><%= @follower_amount %></span>
    <%= link_to 'follow', follow_user_path(id: @user.id) %>
    </li>
    <li class="list-group-item">
    <span class="badge"><%= @followed_amount %></span>
    <%= link_to 'follower', follower_user_path(id: @user.id) %>
    </li>
  </ul>
  <ul class="list-group">
    <li class="list-group-item">
    <span class="badge"><%= @fav_count %></span>
    <%= link_to 'お気に入り一覧', favorites_user_path(id: @user.id) %>
    </li>
  </ul>
  </div>

  <div class="col-sm-6">
    <h3>最近のプレイリスト</h3>

    <table class="table table-striped table-hover ">
      <thead>
        <tr>
          <th>プレイリスト名</th>
          <th>お気に入り数</th>
          <th>更新日時</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <% @playlists.each do |playlist| %>
            <td>
              <%= link_to playlist.title, playlist_path(playlist.id) %>
            </td>
            <td>
              <%= playlist.favorites.count %>
            </td>
            <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>