config/routes.rb
Rails.application.routes.draw do

  root 'playlists#top_page'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

  resources :playlists do
    resources :comments, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :favorites, only: [:create] do
      collection do
        delete '/:user_id', controller: :favorites, action: :destroy, as: :destroy
      end
    end
    resources :musics, only: [:new, :create, :destroy] do
      collection do
        post :search
      end
    end
    collection do
      get :timeline
      get :ranking
      get :genre
      get 'genre/:id', controller: :playlists, action: :each_genre, as: :each_genre
    end
  end

  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :favorites
      get :follow
      get :follower
    end
  end

  namespace :admin do
    resources :playlists, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  attr_accessor :title, :comment, :genre, :count_fav
  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :musics
  enum genre: %i(pops rock jazz classic others)
  validates :title, presence: true
  

  def self.ranking(date, genre)
    if date.present?
      case date
      when "today"
        from = Time.now.at_beginning_of_day
        to = from + 1.day
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      when "week"
        from = Time.now.at_beginning_of_week
        to = from + 1.week
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      when "month"
        from = Time.now.at_beginning_of_month
        to = from + 1.month
        self.where(created_at: from...to).order(count_fav: :desc, created_at: :desc).limit(20)
      end
    elsif genre.present?
      case genre
      when "pops"
        self.where(genre: 0).order(count_fav: :desc, created_at: :desc).limit(10)
      when "rock"
        self.where(genre: 1).order(count_fav: :desc, created_at: :desc).limit(10)
      when "jazz"
        self.where(genre: 2).order(count_fav: :desc, created_at: :desc).limit(10)
      when "classic"
        self.where(genre: 3).order(count_fav: :desc, created_at: :desc).limit(10)
      when "others"
        self.where(genre: 4).order(count_fav: :desc, created_at: :desc).limit(10)
      end
    else
      self.order("count_fav DESC, created_at DESC").limit(20)
    end
  end

  #playlistのデータ使ってないじゃん
  #date, genre両方引数にとったらこんらん
  #他の人だったらどう使うか、伝わりやすさが大事
  #意図が伝わりやすく
  #メソッドだけで表しづらければクラスを作ってしまう。
  #引数わかりやすく
  #プログラミングは思いやり。そもそも読みやすくしてある理由を考える。複数人での開発がスムーズにいくようにする意識を持つ。
  def date_ranking_title(date)
      case date
      when "today"
        "本日のランキング"
      when "week"
        "週間ランキング"
      when "month"
        "月間ランキング"
      end
  end
  
  def genre_ranking_title(genre)
      case genre
      when "pops"
        "PopsランキングTop10"
      when "rock"
        "RockランキングTop10"
      when "jazz"
        "JazzランキングTop10"
      when "classic"
        "ClassicランキングTop10"
      when "others"
        "OthersランキングTop10"
      end
  end

end

app/controllers/admin/playlists_controller.rb
class Admin::PlaylistsController < Admin::AdminController
  def index
    @playlists = Playlist.all.order("updated_at DESC")
    @playlist_user_ids = @playlists.pluck(:user_id)
    @user_name_array = Array.new
    @playlist_user_ids.each do |user_id|
      user_name = User.find(user_id).name
      @user_name_array << user_name
    end
  end

  def show
    @playlist = Playlist.find(params[:id])
    @user = User.find(@playlist.user_id)
    @comments = Comment.where(playlist_id: params[:id])
    @comment_user_ids = @comments.pluck(:user_id)
    ## @user_ids をわかりやすい命名に
    ### 変数多い
    #viewで使わない変数は＠をつけない
    @user_name_array = Array.new
    @comment_user_ids.each do |user_id|
      user_name = User.find(user_id).name
      @user_name_array << user_name
    end
    #インスタンスメソッドとレシーバを意識して、ここのメソッドを修正
    @musics = Music.where(playlist_id: params[:id])
    music = Music.new(playlist_id: params[:id])
    @http = music.http
  end

  def destroy
    @playlist = Playlist.find_by(id: params[:id])
    @playlist.destroy
    redirect_to admin_playlists_path
  end



end

app/controllers/playlists_controller.rb
require 'rubygems'
require 'httparty'

class PlaylistsController < UsersController

  def after_sign_in_path_for(user)
    ranking_playlists_path
  end

#  before_action :authenticate_user!, except: :top_page
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  def top_page
    render layout: 'top_page'
  end

  def index
    @playlists = Playlist.all.order("updated_at DESC")
  end

  def show
    @playlist = Playlist.find(params[:id])
    @comments = Comment.where(playlist_id: params[:id])
    @status = Relationship.where(follower_id: current_user.id, followed_id: @playlist.user.id).present?
    favorite = Favorite.find_by(playlist_id: params[:id], user_id: current_user.id)
    if favorite.present?
      @condition = true
    else
      @condition = false
    end
    music = Music.new(playlist_id: params[:id])
    @http = music.movie_http
  end

  def new
    @playlist = Playlist.new
  end

  def create
    playlist = Playlist.new(playlist_params)
    if playlist.save
      redirect_to playlists_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to playlist_path(id: params[:id])
    else
      flash[:alert] = "Can't be blank!"
      render 'edit'
    end
  end

  def destroy
    playlist = Playlist.find(params[:id])
    playlist.destroy
    redirect_to playlists_path
  end

  def timeline
    follows = Relationship.where(follower_id: current_user.id).pluck(:followed_id)
    @follows = User.where(id: follows)
    @playlists = Playlist.where(user_id: follows).order("updated_at DESC").limit(20)
  end

  def genre
  end

  def each_genre
    @genre = params[:id]
    @playlists = Playlist.where(genre: @genre)
  end

  ## ここにも怪しげなコードがあった
  def ranking
    @playlists = Playlist.ranking(params[:date], params[:genre])
    @playlist_user_ids = @playlists.pluck(:user_id)
    playlist = Playlist.new
    #変なインスタンスメソッドを作って使用しているが、classを作ってやり直すのは時間かかるということでしのさんと話し、ここはそのままで。
    if params[:date].present?
      @title = playlist.date_ranking_title(params[:date])
    elsif params[:genre].present?
      @title = playlist.genre_ranking_title(params[:genre])
    else
      @title = "総合ランキング"
    end
  end

  private
  def playlist_params
    params.require(:playlist).permit(:user_id, :title, :comment, :genre)
  end
  
  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/helpers/admin/playlists_helper.rb
module Admin::PlaylistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_admin_check.html.erb
<% if admin_signed_in? %>
  <%= link_to '削除する', playlists_path %>
<% else %>
<% end %>

app/views/playlists/_comment.html.erb
<%= form_for [@playlist, @playlist.comments.build], :remote => true do |f| %>
  <fieldset>
    <legend>Comment</legend>
    <div class="form-group">
      <div class="col-lg-10">
        <%= f.text_area :content, class: "form-control", placeholder: "Comment"  %>
        <%= f.hidden_field :playlist_id, :value => @playlist.id %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.submit :value => "Send Comment", class: "btn btn-primary btn-xs" %>
      </div>
    </div>
  </fieldset>
<% end %>

app/views/playlists/_form.html.erb
<%= form_for @playlist do |f| %>

  <fieldset>
    <legend>Legend</legend>
    <div class="form-group">
      <%= f.label :Title, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_field :title, class: "form-control", placeholder: "Title" %>
      </div>
    </div>
    <div class="form-group">
      <%= f.label :Comment, class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.text_area :comment, class: "form-control", rows: 3, placeholder: "Comment" %>
      </div>
    </div>


    <div class="form-group">
      <%= f.label :Genre,  class: "col-lg-2 control-label" %>
      <div class="col-lg-10">
        <%= f.select(:genre, options_for_select([["Pops", "pops"], ["Rock", "rock"], ["Jazz", "jazz"], ["Classic", "classic"], ["Others", "others"]]), {class: "form-control", id: "select"}) %>

      </div>
    </div>

    <div>
      <%= f.hidden_field :user_id, :value => current_user.id %>
    </div>

    <div class="form-group">
      <div class="col-lg-10 col-lg-offset-2">
        <%= f.submit :value => "プレイリスト登録", class: "btn btn-primary" %>  
      </div>
    </div>

    </fieldset>
  <% end %>

app/views/playlists/_music_url.html.erb
<%= form_for @music, url: {controller: :playlists, action: :music_create} do |f| %>

    <p>Title & Artist can be blank!</p>

  <div>
    <%= f.hidden_field :playlist_id, value: @playlist.id %>
  </div>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div>
    <%= f.label "Youtube URL" %>
    <%= f.text_field :url %>
  </div>

  <div>
    <%= f.submit "追加" %>
  </div>

<% end %>

app/views/playlists/_profile.html.erb
<div>
  名前：<br />
  <%= @user.name %><br />
</div>

<div>
  性別：<br />
  <%= @user.gender %><br />
</div>

<div>
  <% if @user.bd_open %>
    年齢：<br />
    <% d1 = @user.birth_date.strftime("%Y%m%d").to_i %>
    <% d2 = Date.today.strftime("%Y%m%d").to_i %>
    <%= (d2 - d1)/10000 %>歳
  <% else %>
    非公開
  <% end %><br />
</div>

<div>
  好きな音楽のジャンル：<br />
  <%= @user.fav_music_genre %><br />
</div>

<div>
  自己紹介：<br />
  <%= @user.comment %>
</div>

<div>
  <%= link_to 'follow', playlists_path %>
  <%= link_to 'follower', playlists_path %>
</div>

app/views/playlists/all_fav.html.erb
<h2>お気に入り一覧</h2>

<div>
  <ol>
    <% @favorite.each do |favorite| %>
      <li>
        <% @fav_playlist = @playlist.find_by(:id => favorite.playlist_id) %>
        <%= link_to @fav_playlist.title, playlist_path(favorite.playlist_id) %>
        <%= link_to 'お気に入りから削除', remove_fav_playlist_path(:id => @fav_playlist.id), method: :delete, data: {confirm: "Are you sure?"} %>
      </li>
    <% end %>
  </ol>
</div>

app/views/playlists/create.js.erb
var comments_list = $('#comments-list');
comments_list.append('<%= escape_javascript(render partial: @comment) %>');
comments_list.find('div:last-child').addClass('last-comment');
$('#comments-count').html('This article has <%= escape_javascript(pluralize(@post.comments.count, 'comment')) %>');
// The following is not final implementation
$('#comment_author').val('');
$('#comment_email').val('');
$('#comment_content').val('');

app/views/playlists/each_genre.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <div class="btn-group-vertical">
      <h4>
        ジャンル一覧
      </h4>
      <a>
        <%= link_to 'Pops', each_genre_playlists_path(:id => 0), class: "btn btn-default"  %>
      </a>

      <a>
        <%= link_to 'Rock', each_genre_playlists_path(:id => 1), class: "btn btn-default"  %>
      </a>

      <a>
        <%= link_to 'Jazz', each_genre_playlists_path(:id => 2), class: "btn btn-default"  %>
      </a>

      <a>
        <%= link_to 'Classic', each_genre_playlists_path(:id => 3), class: "btn btn-default"  %>
      </a>

      <a>
        <%= link_to 'Others', each_genre_playlists_path(:id => 4), class: "btn btn-default"  %>
      </a>
      </div>
    </div>

    <h2>
      <% case @genre
        when "0" %> 
        Pops
      <% when "1" %>
        Rock
      <% when "2" %>
        Jazz
      <% when "3" %>
        Classic
      <% when "4" %>
        Others
      <% else %>
        存在しないジャンルです
      <% end %>
    </h2>
    <div class="col-sm-10">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>プレイリスト名</th>
            <th>お気に入り数</th>
            <th>更新日時</th>
          </tr>
        </thead>
        <% @playlists.each do |playlist| %>
          <tbody>
            <tr>
              <td>
                <%= link_to playlist.user.name, user_path(id: playlist.user.id) %>
                </td>
              <td>
                <%= link_to playlist.title, playlist_path(id: playlist.id) %>
                </td>
              <td>
                <%= playlist.favorites.count %>
                </td>
              <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
                </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </ol>
  </div>
</div>
</div>

app/views/playlists/genre.html.erb
<h2>ジャンル別</h2>

<h3>
<%= link_to 'Pops', each_genre_playlists_path(:id => 0) %>
</h3>

<h3>
<%= link_to 'Rock', each_genre_playlists_path(:id => 1) %>
</h3>

<h3>
<%= link_to 'Jazz', each_genre_playlists_path(:id => 2) %>
</h3>

<h3>
<%= link_to 'Classic', each_genre_playlists_path(:id => 3) %>
</h3>

<h3>
<%= link_to 'Others', each_genre_playlists_path(:id => 4) %>
</h3>

app/views/playlists/music_new.html.erb
<h2>曲の登録</h2>

<h4>プレイリスト情報</h4>
タイトル：
<%= @playlist.title %>
<br>
作者からのコメント：
<%= @playlist.comment %>
<br>
登録された曲一覧：
<div>
<% if @musics.nil? %>
  まだ登録されていません。
<% else %>
  <% @musics.each do |music| %>
    <li>
      Music Title : 
      <%= music.title %>
      <% if params[:nextPageToken].nil? %>
      <% @pageToken = params[:nextPageToken] %>
    <% elsif %>
      <% @pageToken = params[:prevPageToken] %>
    <% else %>
      <% @pageToken = nil %>
    <% end %>
      <%= link_to 'プレイリストから外す', music_destroy_playlist_path(id: @playlist.id, music_id: music.id, keyword: @keyword, pageToken: @pageToken), method: :delete, data: {confirm: "Are you sure?"} %>
      <div>
      <iframe width="160" height="90" src="https://www.youtube.com/embed/<%= music.url %>" frameborder="0" allowfullscreen> 
      </iframe>
      </div>

      <br>
 
      </li>
    <% end %>
<% end %>
</div>

<div>
  <%= link_to 'プレイリスト作成を終了する', playlist_path(id: @playlist.id) %>
</div>

<br>

<div>
  <%= form_tag({controller: "playlists", action: "search", id: @playlist.id}) do |f| %>
    <%= label_tag "search[keyword]" %>
    <%= text_field_tag "search[keyword]" %>
    <%= submit_tag "検索"%>
  <% end %>
</div>

<br>
<div>
  『<%= params[:keyword] %>』の検索結果
  </div>

  <br>

<div>
  <%= link_to '前の20件', music_new_playlist_path(id: @playlist.id, keyword: @keyword, prevPageToken: @prevPageToken) unless @prevPageToken.nil? %>
  <%= link_to '最初の20件', music_new_playlist_path(id: @playlist.id, keyword: @keyword) %>
  <%= link_to '次の20件', music_new_playlist_path(id: @playlist.id, keyword: @keyword, nextPageToken: @nextPageToken) unless @nextPageToken.nil? %>
  </div>

<br>

<% @all_response.each do |response| %>
  <div>
    タイトル：
    <%= @title = response["snippet"]["title"] %>
    <br>
    <% @video_id = response["id"]["videoId"] %>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/<%= @video_id %>" frameborder="0" allowfullscreen> 
    </iframe>
    <%= form_for @music, url: {controller: :playlists, action: :music_create} do |f| %>
      <%= f.hidden_field :playlist_id, value: @playlist.id %>
      <%= f.hidden_field :video_id, value: @video_id%>
      VideoId
      <%= @video_id%>
      <%= f.hidden_field :title, value: @title%>
      <%= f.hidden_field :pageToken, value: params[:pageToken] unless params[:pageToken] %>
      <%= f.hidden_field :keyword, value: params[:keyword] unless params[:keyword] %>
      <% if @musics.find_by(url: @video_id).blank? %>
      <%= f.submit "プレイリストに追加" %>
      <% else %>
        この曲は既にプレイリストに登録されています。
    <% end %>
    <% end %>
  </div>
<% end %> 

<div>
  <%= link_to 'プレイリスト作成を終了する', playlist_path(id: @playlist.id) %>
</div>

app/views/playlists/new.html.erb
<h2>プレイリスト作成</h2>

<%= render 'form' %>

app/views/playlists/profile.html.erb
<h2>プロフィール</h2>

<%= render 'profile' %>

<h3>新着プレイリスト</h3>
<ol>
  <% @playlist.each do |playlist| %>
    <li>
      <%= link_to playlist.title, playlist_path(playlist.id) %>
    </li>
  <% end %>
</ol>

app/views/playlists/timeline.html.erb
<h2>タイムライン</h2>

<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <h5>フォロー一覧</h5>
      <div class="btn-group-vertical">
        <% @follows.each do |follow| %>
          <%= link_to follow.name, user_path(id: follow.id), class: "btn btn-default" %>
          <%= link_to "フォロー解除", user_relationship_path(user_id: follow.id, id: current_user.id), class: "btn btn-link btn-xs", method: :delete, data: {confirm: "Are you sure?"} %>
        <% end %>
      </div>
    </div>
    <div class="col-sm-9">
      <table class="table table-striped table-hover ">
        <thead>
          <tr>
            <th>ユーザー名</th>
            <th>プレイリスト名</th>
            <th>お気に入り数</th>
            <th>更新日時</th>
          </tr>
        </thead>
        <% @playlists.each do |playlist| %>
          <tbody>
            <tr>
              <td>
                <%= link_to playlist.user.name, user_path(id: playlist.user.id) %>
              </td>
              <td>
                <%= link_to playlist.title, playlist_path(id: playlist.id) %>
              </td>
              <td>
                <%= playlist.favorites.count %>
              </td>
            <td>
              <% update_time = playlist.updated_at %>
              <%= update_time.strftime("%Y-%m-%d %H:%M:%S") %>
              </td>
            </tr>
          </tbody>
        <% end %>
      </table>
    </div>
  </div>

app/views/playlists/top_page.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-6">
      <h2><%= link_to 'ログイン', new_user_session_path, class: "btn btn-primary btn-lg" %></h2>
    </div>

    <div class="col-sm-6">
      <h2><%= link_to '新規登録', new_user_registration_path, class: "btn btn-primary btn-lg"%></h2>
    </div>

    <div><%= link_to 'Forget your password?', new_user_password_path, class: "btn btn-link btn-lg" %></div>

  </div>
</div>