config/routes.rb
Rails.application.routes.draw do

  root 'playlists#top_page'

  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations'
  }
  devise_for :admins, :controllers => {
    :sessions => 'admin/sessions',
    :registrations => 'admin/registrations'
  }

  resources :playlists do
    resources :comments, only: [:index, :create, :new, :edit, :update, :destroy]
    resources :favorites, only: [:create] do
      collection do
        delete '/:user_id', controller: :favorites, action: :destroy, as: :destroy
      end
    end
    resources :musics, only: [:new, :create, :destroy] do
      collection do
        post :search
      end
    end
    collection do
      get :timeline
      get :ranking
      get :genre
      get 'genre/:id', controller: :playlists, action: :each_genre, as: :each_genre
    end
  end

  resources :users, only: [:show] do
    resources :relationships, only: [:create, :destroy]
    member do
      get :favorites
      get :follow
      get :follower
    end
  end

  namespace :admin do
    resources :playlists, only: [:index, :show, :destroy] do
      resources :comments, only: [:index, :destroy]
    end
    resources :users, only: [:index, :show, :destroy]
  end

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Music Cafe For Admin</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <% if flash[:alert] %>
      <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Warning!</h4>
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>


    <% if flash[:notice] %>
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Notice!</h4>
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <div class="btn-group">
    <%= link_to 'Admin Sign out', destroy_admin_session_path, method: :delete, class: "btn btn-link btn-xs pull-right" %>
    </div>

    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
        <ul class="nav navbar-nav">
          <li>
          <%= link_to 'プレイリスト一覧', admin_playlists_path %>
          </li>
          <li>
          <%= link_to 'ユーザー一覧', admin_users_path %>
          </li>
        </ul>
      </div>
    </div>
    </nav>


    <style>
      header.jumbotron {
        background-image: url(/assets/cafe.image1.jpg);
        background-position: center center;
        background-size: cover;
        color: #fff;
      }

      header .container {
        margin-top: 13%;
      }

    </style>

  </head>
  <body>

    <header class="jumbotron">
    <div class="container">
      <h1>Music Cafe For Admin</h1>
    </div>
    </header>

    <div class="container-fluid">
      <%= yield %>
    </div>

  </body>
</html>

app/views/layouts/admins.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <div>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
  </div>

  <div>
    <% if flash[:alert] %>
      <%= flash[:alert] %>
    <% end %>
  </div>

  <%= link_to 'Admin Sign out', destroy_admin_session_path, method: :delete %>
  <%= link_to 'Edit your profile', edit_admin_registration_path %><br />
  <%= link_to '新着プレイリスト', admin_playlists_path %>
  <%= link_to 'ジャンル', admin_genre_playlists_path %>
  <%= link_to 'ランキング', ranking_admin_playlists_path %>
  <%= link_to 'お気に入り一覧', all_fav_admin_playlists_path %>
  <%= link_to 'マイページ', mypage_admin_user_infos_path %>
</head>
<body>

<%= yield %>
<br />
<%= link_to 'Topへ戻る', admin_playlists_path %>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Music Cafe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <% if flash[:alert] %>
      <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Warning!</h4>
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>


    <% if flash[:notice] %>
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Notice!</h4>
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

      <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-link btn-xs pull-right" %>
      <%= link_to 'Edit your profile', edit_user_registration_path, class: "btn btn-link btn-xs pull-right" %><br />

    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
        <ul class="nav navbar-nav">
          <li>
          <%= link_to '新着プレイリスト', playlists_path %> 
          </li>
          <li>
          <%= link_to 'タイムライン', timeline_playlists_path %>
          </li>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ジャンル<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
            <%= link_to 'Pops', each_genre_playlists_path(:id => 0) %>
            </li>
            <li>
            <%= link_to 'Rock', each_genre_playlists_path(:id => 1) %>
            </li>
            <li>
            <%= link_to 'Jazz', each_genre_playlists_path(:id => 2) %>
            </li>
            <li>
            <%= link_to 'Classic', each_genre_playlists_path(:id => 3) %>
            <li>
            <%= link_to 'Others', each_genre_playlists_path(:id => 4) %>
            </li>
          </ul>
          </li>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ランキング<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
            <%= link_to '総合ランキング', ranking_playlists_path %>
            </li>
            <li class="divider">Date</li>
            <li>
            <li>
            <%= link_to '本日のランキング', ranking_playlists_path(date: "today") %>
            </li>
            <li>
            <%= link_to '週間ランキング', ranking_playlists_path(date: "week") %>
            </li>
            <li>
            <%= link_to '月間ランキング', ranking_playlists_path(date: "month") %>
            </li>
            <li class="divider">Genre</li>
            <li>
            <%= link_to 'Pops Top10', ranking_playlists_path(genre: "pops") %>
            </li>
            <li>
            <%= link_to 'Rock Top10', ranking_playlists_path(genre: "rock") %>
            </li>
            <li>
            <%= link_to 'Jazz Top10', ranking_playlists_path(genre: "jazz") %>
            </li>
            <li>
            <%= link_to 'Classic Top10', ranking_playlists_path(genre: "classic") %>
            </li>
            <li>
            <%= link_to 'Others Top10', ranking_playlists_path(genre: "others") %>
            </li>
          </ul>
          </li>
          <li>
          <%= link_to 'お気に入り一覧', favorites_user_path(id: current_user.id) %>
          </li>
          <li>
          <%= link_to 'マイページ', user_path(id: current_user.id) %>
          </li>
        </div>
      </div>


      <style>
        header.jumbotron {
          background-image: url(/assets/cafe.image1.jpg);
          background-position: center center;
          background-size: cover;
          color: #fff;
        }

        header .container {
          margin-top: 13%;
        }

      </style>

    </head>
    <body>

      <header class="jumbotron">
      <div class="container">
        <h1>Music Cafeへようこそ</h1>
      </div>
      </header>

      <div class="container-fluid">
        <%= yield %>
        <br />
        <%= link_to 'プレイリストを作る', new_playlist_path, class: "btn btn-primary" %>
        <br />
        <%= link_to 'Topへ戻る', playlists_path, class: "btn btn-link" %>

      </div>
    </body>
  </html>

app/views/layouts/playlist_bootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>Bootstrap 101 Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

      <style>
        header.jumbotron {
          background-image: url(/assets/jazz.image1.jpg);
          background-position: center center;
          background-size: cover;
          color: #fff;
        }

      </style>
  </head>
  <body>

    <div class="jumbotron">
        <h1>Jumbotron</h1>
          <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
            <p><a class="btn btn-primary btn-lg">Learn more</a></p>

    <%= yield %>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="js/bootstrap.min.js"></script>
          </div>
  </body>
</html>

app/views/layouts/profile.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Music Cafe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <div>
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    </div>

    <div>
      <% if flash[:alert] %>
        <%= flash[:alert] %>
      <% end %>
    </div>

    <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
    <%= link_to 'Edit your profile', edit_user_registration_path %><br />

    <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-collapse collapse" id="bs-example-navbar-collapse-1" aria-expanded="false" style="height: 1px;">
        <ul class="nav navbar-nav">
          <li>
          <%= link_to '新着プレイリスト', playlists_path %> 
          </li>
          <li>
          <%= link_to 'タイムライン', timeline_playlists_path %>
          </li>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ジャンル<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
            <%= link_to 'Pops', each_genre_playlists_path(:id => 0) %>
            </li>
            <li>
            <%= link_to 'Rock', each_genre_playlists_path(:id => 1) %>
            </li>
            <li>
            <%= link_to 'Jazz', each_genre_playlists_path(:id => 2) %>
            </li>
            <li>
            <%= link_to 'Classic', each_genre_playlists_path(:id => 3) %>
            <li>
            <%= link_to 'Others', each_genre_playlists_path(:id => 4) %>
            </li>
          </ul>
          </li>
          <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">ランキング<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li>
            <%= link_to '総合ランキング', ranking_playlists_path %>
            </li>
            <li class="divider">Date</li>
            <li>
            <li>
            <%= link_to '本日のランキング', ranking_playlists_path(date: "today") %>
            </li>
            <li>
            <%= link_to '週間ランキング', ranking_playlists_path(date: "week") %>
            </li>
            <li>
            <%= link_to '月間ランキング', ranking_playlists_path(date: "month") %>
            </li>
            <li class="divider">Genre</li>
            <li>
            <%= link_to 'Pops Top10', ranking_playlists_path(genre: "pops") %>
            </li>
            <li>
            <%= link_to 'Rock Top10', ranking_playlists_path(genre: "rock") %>
            </li>
            <li>
            <%= link_to 'Jazz Top10', ranking_playlists_path(genre: "jazz") %>
            </li>
            <li>
            <%= link_to 'Classic Top10', ranking_playlists_path(genre: "classic") %>
            </li>
            <li>
            <%= link_to 'Others Top10', ranking_playlists_path(genre: "others") %>
            </li>
          </ul>
          </li>
          <li>
          <%= link_to 'お気に入り一覧', my_favorites_users_path %>
          </li>
          <li>
          <%= link_to 'マイページ', mypage_users_path %>
          </li>
        </div>
      </div>

      <style>
        header.jumbotron {
          background-image: url(/assets/cafe.image1.jpg);
          background-position: center center;
          background-size: cover;
          color: #fff;
        }

        header .container {
          margin-top: 13%;
        }

      </style>

    </head>
    <body>

      <header class="jumbotron">
        <div class="container">
          <h1>Music Cafeへようこそ</h1>
        </div>
      </header>

      <div class="container-fluid">
        <%= yield %>
        <br />
        <%= link_to 'プレイリストを作る', new_playlist_path %>
        <br />
        <%= link_to 'Topへ戻る', playlists_path %>

      </div>
    </body>
  </html>

app/views/layouts/top_page.html.erb
<!DOCTYPE html>
<html>
  <head>

    <title>Music Cafe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <% if flash[:alert] %>
      <div class="alert alert-dismissible alert-warning">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Warning!</h4>
        <p><%= flash[:alert] %></p>
      </div>
    <% end %>


    <% if flash[:notice] %>
      <div class="alert alert-dismissible alert-success">
        <button type="button" class="close" data-dismiss="alert">×</button>
        <h4>Notice!</h4>
        <p><%= flash[:notice] %></p>
      </div>
    <% end %>

    <style>
      header.jumbotron {
        background-image: url(/assets/jazz.image2.jpg);
        background-position: center center;
        background-size: cover;
        color: #fff;
      }

      header .container {
        margin-top: 25%;
      }

    </style>

  </head>
  <body>

    <h1>Music Cafeへようこそ</h1>

    <header class="jumbotron">
    <div class="container">
    </div>
    </header>


    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>